services:
  db:
    image: pgvector/pgvector:pg17
    platform: linux/arm64
    container_name: sherwood-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sherwood_db
    ports:
      - "5432:5432"
    volumes:
      - sherwood-data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    platform: linux/arm64
    container_name: sherwood-ollama
    ports:
      - "11434:11434"

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data

volumes:
  sherwood-data: {}
  minio-data: {}